#pragma once

// Observation assembly for diffsimrl G1 motion-tracking policies (ADD/AMP).
//
// Deliberately free of ROS, MuJoCo and ONNX Runtime: it needs Eigen and
// yaml-cpp (which parses the exporter's JSON -- JSON is a subset of YAML) and
// nothing else. That keeps it unit-testable against a golden trace recorded
// from diffsimrl itself (see tests/difftrack_selftest.cpp), which is the only
// real way to know a reimplementation of somebody else's observation is right:
// the failure modes are quiet ones -- a transposed rotation column, a joint
// permutation, an off-by-one in the lookahead -- that produce a plausible
// vector and a robot that falls over for no visible reason.
//
// Everything here is generated by
//   diffsimrl/code/scripts/export_to_drcl_cpp_control.py
// which writes difftrack_config.json + motion.bin + policy.onnx into
// models/tracker/difftrack/<motion>/.
//
// The observation is 849-dim for the shipped tracking runs:
//
//   char_obs  237  the robot's own state, world frame
//   tar_obs   612  three future reference frames (3 x 204)
//
// char_obs and tar_obs are both expressed in the WORLD frame (the policies were
// trained with imitation.global_obs=true), so the caller must supply a genuine
// world root pose and world linear velocity -- an IMU alone cannot do it. In
// mj_sim that is ground truth off the pelvis framepos/framelinvel/frameangvel
// sensors (G1State.base_pose / base_twist); on hardware it needs a motion
// capture system or an equivalent state estimator.
//
// This file is a port of crl-humanoid-ros' crl_g1_mimiccontroller/DiffTrackObs,
// where these policies were first deployed. The arithmetic is unchanged and is
// held to the same golden trace; only the JSON reader (nlohmann -> yaml-cpp,
// to add no dependency this package did not already have) and the namespace
// differ.

#include <Eigen/Dense>
#include <Eigen/Geometry>

#include <string>
#include <vector>

namespace cpp_control::g1::difftrack {

    /**
     * Rigid placement of the reference clip in the world.
     *
     * Because the observation is world-frame, the policy sees where the clip is
     * in absolute terms. When the episode starts with the robot teleported onto
     * the clip's first frame (reference-state initialisation, what these policies
     * were validated with) that is exactly right and the anchor is the identity.
     *
     * When the robot instead starts wherever it happens to be standing -- always
     * the case on hardware -- the clip has to be moved to it, or the very first
     * observation reports a metres-large position error and a policy trained only
     * on near-zero error is being asked to extrapolate.
     *
     * The transform is deliberately restricted to yaw and horizontal translation:
     *
     *     p -> [Rz(yaw) * p.xy + t,  p.z]        q -> Rz(yaw) * q
     *
     * Height and tilt are left alone -- they are measured against the floor, which
     * does not move, and rotating the clip out of the horizontal plane would ask
     * the policy to track a motion that leans.
     *
     * ROTATING THE CLIP IN THE WORLD IS NOT FREE. These policies were trained
     * with ``imitation.global_obs=true``: the observation carries the root's
     * ABSOLUTE world orientation and its world-frame linear and angular velocity,
     * so the policy is not equivariant to yaw. The translation genuinely cancels
     * -- the reference's position enters the observation relative to the agent in
     * XY, and height is measured against the floor -- but a yaw applied to the
     * clip alone leaves the robot's own orientation and velocity reported in the
     * world frame, which is then a heading the policy never saw at that clip step.
     * Measured on the five shipped lafan1 clips in this workspace's MuJoCo plant,
     * with the observation left in the world frame: a 5 m translation changes the
     * mean root error by less than a millimetre, while a 45 deg rotation roughly
     * quadruples it and 90 deg makes four of five clips fall.
     *
     * That is a property of the OBSERVATION, not of the physics. A yaw about the
     * gravity axis is an exact symmetry of the plant, and the observation is
     * exactly equivariant under it -- rotate the robot and the clip together and
     * every channel rotates with them. So the anchor is safe as long as the robot
     * is rotated with it, which is what toReferenceFrame() does: the clip is
     * placed at the robot in the world, and the observation is then built in the
     * clip's own trained frame, where the policy is back on distribution no matter
     * which way the robot happens to be facing.
     *
     * Use the anchor's yaw ONLY together with toReferenceFrame(). With the
     * observation left in the world frame, keep yaw at 0 and turn the ROBOT onto
     * the clip's heading instead (turn the robot with the locomotion policy, or
     * stand it on the clip's heading by hand).
     */
    struct MotionAnchor {
        double yaw = 0.0;                                   // rotation about +Z
        Eigen::Vector2d translation = Eigen::Vector2d::Zero();
        bool identity = true;

        Eigen::Quaterniond rotation() const {
            return Eigen::Quaterniond(Eigen::AngleAxisd(yaw, Eigen::Vector3d::UnitZ()));
        }
    };

    /**
     * Everything the exporter resolved at build time: the policy's action space,
     * the gains it was trained with, the observation layout, and the kinematic
     * table used to rebuild body poses from joint encoders.
     */
    struct DiffTrackConfig {
        // --- identity -------------------------------------------------------
        std::string sourceRun;
        std::string motionFile;
        // Which training run this directory was exported from, and the tag that
        // keeps it apart from its siblings when several policies of one clip are
        // exported side by side. Both empty for a config exported before they
        // existed, which is why they are read with defaults.
        std::string trainRun;
        std::string variant;
        // Which algorithm trained the policy: forl_shac or ppo. Nothing here
        // depends on it -- the export folds either one's observation
        // normalisation into policy.onnx -- it is reported so a run says which
        // policy it measured. A config without it predates PPO support, when
        // the exporter read forl checkpoints only, so that is the default.
        std::string trainAlg;
        std::string modelName;   // policy.onnx, relative to the config directory
        std::string motionName;  // motion.bin,  relative to the config directory
        int checkpointIter = -1;

        // --- policy ---------------------------------------------------------
        int numObs = 0;
        int numActions = 0;
        double controlDt = 0.02;

        // Policy/action-space joint order -- the training MJCF's. G1Node's own
        // order comes from the task yaml (unitree_hg motor index == the mjlab MJ
        // index). The two happen to agree for the G1, but the node resolves them
        // BY NAME anyway and refuses a name it cannot place: a silent permutation
        // is the one bug in this pipeline that produces no error at all.
        std::vector<std::string> policyJointNames;
        Eigen::VectorXd defaultAngles;      // (numActions)
        double actionScale = 1.0;
        bool actionClipping = false;
        double actionClipRange = 1.0;

        Eigen::VectorXd jointStiffness;     // (numActions) trained PD gains
        Eigen::VectorXd jointDamping;       // (numActions)
        Eigen::VectorXd jointTorqueLimit;   // (numActions)

        double terminationHeight = 0.0;

        // --- observation layout ---------------------------------------------
        bool globalObs = true;
        bool rootHeightObs = true;
        int charObsDim = 0;
        int tarFeatDim = 0;
        int clipSteps = 0;
        double motionLengthS = 0.0;

        // LoopMode.WRAP -- a cyclic clip (the MimicKit walk) that repeats for as
        // long as the robot is asked to track it, rather than ending on a last
        // frame (every lafan1 clip). The table above holds `wrapCycles` whole
        // reference cycles, chosen by the exporter so that they land on a whole
        // number of control steps; replaying it modulo clipSteps and adding
        // `wrapDelta` to every root position each time round is exactly what the
        // training-time motion library does (MotionLib._calc_loop_offset), so the
        // reference is on the same instants it was trained on indefinitely.
        bool loopWrap = false;
        int wrapCycles = 1;
        Eigen::Vector3d wrapDelta = Eigen::Vector3d::Zero();   // per table repeat
        int numBodies = 0;                  // 31 for the G1 MimicKit model
        int numKeyPoints = 0;
        std::vector<int> tarObsSteps;       // lookahead slots, e.g. {1,2,3}

        std::vector<int> keyBodyIds;                 // indices into the body table
        std::vector<Eigen::Vector3d> keyBodyOffsets;  // local offset per key point

        // Per non-root joint j (body j+1): hinge axis and the DOF driving it.
        // dofIndex < 0 marks a welded joint, whose local rotation is identity.
        std::vector<Eigen::Vector3d> dofAxes;   // (numBodies - 1)
        std::vector<int> dofIndex;              // (numBodies - 1)

        // --- kinematic table (MuJoCo's body tree, flattened) ------------------
        std::vector<std::string> bodyNames;
        std::vector<int> parent;
        std::vector<Eigen::Vector3d> bodyPos;
        std::vector<Eigen::Quaterniond> bodyQuat;
        std::vector<Eigen::Vector3d> jointAxis;
        std::vector<int> jointDof;              // -1 => welded to parent
        std::vector<Eigen::Vector3d> fixedOffset;

        // --- reference-state initialisation (clip frame 0) --------------------
        struct Rsi {
            Eigen::Vector3d rootPos = Eigen::Vector3d::Zero();
            Eigen::Quaterniond rootQuat = Eigen::Quaterniond::Identity();
            Eigen::Vector3d rootLinVel = Eigen::Vector3d::Zero();
            Eigen::Vector3d rootAngVelWorld = Eigen::Vector3d::Zero();
            Eigen::VectorXd dofPos;
            Eigen::VectorXd dofVel;
        } rsi;
    };

    /**
     * The robot state the observation is built from, in POLICY joint order and
     * WORLD frame.
     */
    struct DiffTrackState {
        Eigen::Vector3d rootPos = Eigen::Vector3d::Zero();
        Eigen::Quaterniond rootQuat = Eigen::Quaterniond::Identity();
        Eigen::Vector3d rootLinVelWorld = Eigen::Vector3d::Zero();
        Eigen::Vector3d rootAngVelWorld = Eigen::Vector3d::Zero();
        Eigen::VectorXd dofPos;   // (numActions)
        Eigen::VectorXd dofVel;   // (numActions)
    };

    /**
     * The robot's state re-expressed in the reference clip's own frame.
     *
     * @p anchor is the rigid placement of the clip in the world, so this applies
     * its INVERSE to the robot:
     *
     *     p_ref = Rz(-yaw) * (p_world - [t, 0])      q_ref = Rz(-yaw) * q_world
     *
     * and the same rotation to both velocities. Joint positions and velocities
     * are frame-free and pass through.
     *
     * Feeding computeObs() the result together with an IDENTITY anchor is what
     * makes a yaw anchor safe. The pair (robot, clip) is then in exactly the
     * configuration the policy trained on -- the clip at its recorded world
     * heading, the robot beside it -- whichever way the real robot is facing.
     * The action that comes back is a joint-position target, which carries no
     * frame with it, so nothing has to be rotated on the way out.
     */
    DiffTrackState toReferenceFrame(const DiffTrackState &world, const MotionAnchor &anchor);

    /**
     * One SYNTHESISED reference frame -- a lead-in step, a blend-in step or a
     * blend-out step -- already placed in the world (the anchor has been
     * applied), in the same pieces the clip table stores: root pose, local joint
     * rotations as tan-norm 6-vectors, and key points relative to the root.
     *
     * Anywhere one of these exists for an episode step it REPLACES the clip's
     * own frame at that step, for the lookahead the policy is shown and for the
     * reference the tracking error is measured against alike.
     */
    struct SynthFrame {
        Eigen::Vector3d rootPos = Eigen::Vector3d::Zero();
        Eigen::Quaterniond rootQuat = Eigen::Quaterniond::Identity();
        Eigen::VectorXd dofPos;         // (numActions), for the ghost/diagnostics
        std::vector<float> jointRot6;   // 6 * (numBodies - 1)
        std::vector<float> keyRel;      // 3 * numKeyPoints

        /**
         * Whether rootPos/rootQuat/keyRel already have the anchor in them.
         *
         * The lead-in is built in the WORLD (true): it is an approach from where
         * the robot physically is, and the robot is not in the clip's frame. The
         * blends are built in the CLIP's own frame (false) and are anchored on the
         * way out, exactly as the clip's table is -- which is what lets them be
         * read back through the IDENTITY anchor that `observe_in_reference_frame`
         * uses, the thing the lead-in cannot do and is refused for.
         */
        bool anchored = true;
    };

    /**
     * Loads the exported artifacts and turns robot state into a policy
     * observation. Stateless with respect to the robot: the episode step and the
     * clip's placement are passed in, so the caller owns the tracking clock.
     */
    class DiffTrackObsBuilder {
    public:
        /**
         * Load difftrack_config.json and the motion.bin sitting beside it.
         * Returns false and fills @p error on any inconsistency; the exporter
         * writes the shapes, so a mismatch here means the files disagree.
         */
        bool load(const std::string &configPath, std::string &error);

        const DiffTrackConfig &config() const { return cfg_; }

        /** Control steps in the reference clip. */
        int clipSteps() const { return cfg_.clipSteps; }

        /**
         * True when the clip loops forever instead of ending on a last frame.
         * A looping clip has no natural completion, so the caller has to decide
         * when to stop tracking it (the node's `play_duration` parameter).
         */
        bool loops() const { return cfg_.loopWrap; }

        /** Control steps of synthesised approach before clip frame 0; 0 if none. */
        int leadInSteps() const {
            return leadIn_.empty() ? 0 : static_cast<int>(leadIn_.size()) - 1;
        }

        /** Control steps in the whole episode: lead-in followed by the clip. */
        int episodeSteps() const { return leadInSteps() + cfg_.clipSteps; }

        /**
         * Assemble the policy observation for @p state at @p episodeStep, with the
         * reference clip placed by @p anchor. @p obs is resized to cfg().numObs.
         *
         * @p episodeStep counts from the start of the lead-in when one has been
         * built, so clip frame 0 is at step leadInSteps(). Steps past the end of
         * the clip reuse the final frame, which is what the training-time motion
         * library does under LoopMode.CLAMP.
         */
        void computeObs(const DiffTrackState &state, int episodeStep,
                        const MotionAnchor &anchor, std::vector<float> &obs) const;

        /**
         * The anchor that places clip frame @p episodeStep at the robot's current
         * horizontal position. Used when the episode does not start from
         * reference-state initialisation.
         *
         * @p matchYaw additionally rotates the clip onto the robot's heading, so
         * that clip frame @p episodeStep lands on the robot's pose exactly rather
         * than only on its position. Read MotionAnchor's note before turning it
         * on: it is only safe when the observation is built in the clip's frame
         * via toReferenceFrame().
         */
        MotionAnchor makeAnchor(const Eigen::Vector3d &robotPos,
                                const Eigen::Quaterniond &robotQuat,
                                int episodeStep, bool matchYaw) const;

        /**
         * Build a lead-in: a synthesised reference segment that starts on the
         * robot exactly as it is standing and arrives at the clip's first frame
         * with that frame's pose AND its velocity.
         *
         * Anchoring alone is not enough to start a clip from a standing robot.
         * It puts the reference where the robot is, but every shipped clip begins
         * mid-motion -- 0.33 to 1.49 m/s, in a joint pose radians away from any
         * stand -- so on the very first control step the reference is already
         * running and the robot is not. The tracking error is a metre inside a
         * second, which is far outside anything the policy saw in training.
         *
         * The lead-in removes that step discontinuity by interpolating. Each
         * quantity follows a cubic Hermite in time, clamped to the measured robot
         * state and its zero velocity at one end and to the clip's first frame and
         * ITS velocity at the other, so the reference is C1 across the handover:
         * position and velocity both match where the clip takes over. Choosing the
         * horizontal travel as the trapezoid ``(v0 + v1) * T / 2`` makes the root's
         * translation a constant-acceleration ramp, which is what the anchor's
         * translation is solved for -- the reference accelerates smoothly from the
         * robot's standing speed up to the clip's entry speed rather than jumping.
         *
         * Returns the anchor to use for the whole episode (the clip's placement is
         * a consequence of where the lead-in has to end) and leaves the synthesised
         * frames in the builder. @p durationS <= 0 clears any lead-in and gives the
         * plain anchor of makeAnchor().
         *
         * Measured on the five shipped clips: once the robot is turned onto the
         * clip's heading (@p matchYaw false), a lead-in is NOT what makes a
         * standing start work, and a long one actively breaks it -- the policies
         * have no standing behaviour, so parking them in front of a slow reference
         * topples the robot in about a second. Leave it at 0 unless a specific
         * clip measures better with it.
         */
        MotionAnchor buildLeadIn(const DiffTrackState &robot, double durationS,
                                 bool matchYaw);

        /** Discard a lead-in built earlier (episode restart). */
        void clearLeadIn() { leadIn_.clear(); }

        /**
         * Build a BLEND-IN: the clip's own first @p durationS of reference, eased
         * onto the pose the robot is actually standing in.
         *
         * This is the lead-in's answer to the same problem -- a clip that starts
         * mid-motion cannot be handed to a standing robot -- taken from the other
         * end. A lead-in PREPENDS a synthesised approach, so the clip starts late
         * and the policy spends the approach being asked to move slowly; a
         * tracking policy has no slow gear, and that is the configuration measured
         * to topple the robot in about a second.
         *
         * The blend-in delays nothing and slows nothing. The clip's clock runs at
         * 1x from episode step 0, so every lookahead the policy is shown has the
         * timing it trained on. What is interpolated is only the robot's
         * DISAGREEMENT with clip frame 0, faded out on a smoothstep:
         *
         *     reference(j) = clip(j) + a(j) * (robot - clip(0))
         *
         * for the root position, the root orientation (as a rotation vector) and
         * the joint angles alike, with a(0) = 1 and a(steps) = 0 and zero slope at
         * both ends. Step 0 is therefore exactly the pose the robot is standing
         * in, the clip's own motion is underneath from the first step, and the
         * standing pose bleeds out from under it.
         *
         * WHERE THE CLIP IS PLACED is makeAnchor's placement, unchanged: frame 0
         * on the robot. It is worth saying what is NOT done, because it is the
         * obvious idea and it measured wrong. A standing robot cannot have the
         * clip's entry velocity, so the clip looks like it should be set BACK by
         * the travel the robot gives up while it accelerates -- the lead-in's
         * trapezoid, half a metre on g1_fight. Measured, that makes things worse:
         * the robot does not chase the reference root, it EXECUTES THE MOTION, and
         * the motion carries the root the clip's own distance whatever the root
         * reference says. Setting the clip back does not close the error, it opens
         * a permanent one -- 0.47 m of standing offset for the rest of the run,
         * against 0.1 m with the plain anchor.
         *
         * MEASURED, on unitree_mujoco from the SONIC stand, ground-truth world
         * state, `A` pressed after a 4 s settle:
         *
         *     g1_fight      no blend     falls at clip step  73/748, max err 1.82 m
         *                   0.3 s                            95/748,         1.74 m
         *                   0.5 s                           114/748,         0.70 m
         *                   1.0 s                           113/748,         0.76 m
         *                   1.5 s                            61/748,         1.34 m
         *                   2.5 s                            58/748,         1.40 m
         *     g1_dance15s   no blend     650/650 clean, mean err 0.175 m
         *                   1.0 s        650/650 clean,          0.138 m
         *
         * so around 1 s, and it is a real optimum rather than a monotone knob:
         * too short leaves the step change in, too long leaves the reference in a
         * pose that is neither the robot's nor the clip's for long enough to
         * matter. It does NOT make g1_fight survivable from a stand -- see
         * docs/trackers/difftrack_running.md for what that clip's opening costs
         * and why RSI gets away with it.
         *
         * @p durationS <= 0 clears any blend-in and gives the plain anchor of
         * makeAnchor(). @p matchYaw is makeAnchor()'s, with the same caveat. The
         * anchor is returned because the frames are built in the clip's frame and
         * the caller needs the placement they will be read back through.
         */
        MotionAnchor buildBlendIn(const DiffTrackState &robot, double durationS,
                                  bool matchYaw);

        /**
         * Build a BLEND-OUT: the last @p durationS of the played reference, eased
         * off the clip and onto a STANDING pose.
         *
         * The mirror of the blend-in, and it exists for the mirror problem. A clip
         * does not end anywhere a humanoid can stand -- mid-stride, in single
         * support, at up to 1.8 m/s -- and the rest state has to catch the robot
         * from there. Freezing the reference instead (`exit_hold`) measures worse
         * than doing nothing at all: a tracking policy parked on a single-support
         * frame does not brake, it flails.
         *
         * So the reference is given somewhere to go: over the last @p durationS of
         * the run it is INTERPOLATED onto a frame the robot can be handed over
         * from,
         *
         *     reference(j) = (1 - a(j)) * clip(j) + a(j) * stand
         *
         * with a(0) = 0 and a(steps) = 1, zero slope at both ends, where `stand`
         * is
         *
         *   joint angles      the export's own default pose -- the pose the rest
         *                     state is about to ask for, whichever engine backs it.
         *   root orientation  upright, on the heading the clip has at its last
         *                     played frame: the yaw is kept, the lean goes to zero.
         *   root position     that frame's own horizontal position, at the height
         *                     the default pose stands at with its feet on the floor
         *                     the clip is on (standRootHeight). Keeping the
         *                     position means the run still ends where it would have
         *                     ended, so what this changes is the POSE it finishes
         *                     in and not how far it got -- and the reference comes
         *                     to rest there, because a smoothstep onto a fixed
         *                     point has zero velocity at the end.
         *
         * The interpolation is the one asymmetry with the blend-in, which ADDS a
         * fading offset to the clip instead. That is deliberate: the blend-in wants
         * the clip's full amplitude present from the first step, and the blend-out
         * wants it damped out, which is what "comes to rest" means. Adding an
         * offset here would leave the clip dancing at full amplitude into the last
         * step and then ask the reference to reach the standing pose in one of them.
         *
         * MEASURED on g1_dance15s (13 s budget, SONIC stand, ground truth): the
         * reference's distance from the default pose over the last second goes
         * 2.94 -> 1.94 -> 0.91 -> 0.15 rad with a 1 s blend-out against
         * 3.07 -> 3.29 -> 2.19 without, and the robot arrives at the handover 1.2
         * rad from the stand's pose rather than 2.2. The run itself is unharmed:
         * 650/650 clean either way, mean root error 0.138 m with, 0.175 m without.
         *
         * @p lastEpisodeStep is the last step that will be PLAYED, which is not
         * the clip's last frame when `play_duration` cuts the run short -- the
         * blend has to land on the step the handover actually happens at.
         * @p durationS <= 0 clears any blend-out.
         */
        void buildBlendOut(int lastEpisodeStep, double durationS);

        /** Discard both blends (episode restart). */
        void clearBlends() {
            blendIn_.clear();
            blendOut_.clear();
            blendOutFirst_ = -1;
        }

        /** Control steps the blend-in covers; 0 if there is none. */
        int blendInSteps() const {
            return blendIn_.empty() ? 0 : static_cast<int>(blendIn_.size()) - 1;
        }

        /** Control steps the blend-out covers; 0 if there is none. */
        int blendOutSteps() const {
            return blendOut_.empty() ? 0 : static_cast<int>(blendOut_.size()) - 1;
        }

        /**
         * Policy action -> joint position target, in POLICY joint order.
         * target = default + action_scale * action, optionally clipped, exactly
         * as utils/actuator_params.py:process_policy_actions_numpy does.
         */
        void actionToJointTarget(const Eigen::VectorXd &action,
                                 Eigen::VectorXd &target) const;

        /** World body poses for the tracked bodies (exposed for diagnostics). */
        void forwardKinematics(const Eigen::Vector3d &rootPos,
                               const Eigen::Quaterniond &rootQuat,
                               const Eigen::VectorXd &dofPos,
                               std::vector<Eigen::Vector3d> &bodyPos,
                               std::vector<Eigen::Quaterniond> &bodyQuat) const;

        /**
         * Reference root pose and joint pose at @p episodeStep, with @p anchor
         * applied. Used for the tracking-error readout and the ghost overlay.
         * Steps inside the lead-in report the synthesised approach frame.
         */
        void referencePose(int episodeStep, const MotionAnchor &anchor,
                           Eigen::Vector3d &rootPos, Eigen::Quaterniond &rootQuat,
                           Eigen::VectorXd &dofPos) const;

    private:
        DiffTrackConfig cfg_;

        // motion.bin. The reference is stored as raw world-frame pieces rather
        // than as the finished feature vector, because the anchor has to be
        // applied before the 6D rotation encoding is formed -- tan-norm does not
        // commute with a yaw rotation, so a precomputed feature block cannot be
        // rotated after the fact.
        std::vector<float> tarRootPos_;    // (S, clipSteps, 3)      world
        std::vector<float> tarRootQuat_;   // (S, clipSteps, 4)      world, wxyz
        std::vector<float> tarJointRot6_;  // (S, clipSteps, 6*(nb-1)) local, anchor-invariant
        std::vector<float> tarKeyRel_;     // (S, clipSteps, K*3)    world-oriented, root-relative
        std::vector<float> refRootPos_;    // (clipSteps, 3)
        std::vector<float> refRootQuat_;   // (clipSteps, 4)  wxyz
        std::vector<float> refDofPos_;     // (clipSteps, numActions)

        // Synthesised approach onto clip frame 0, indexed by episode step. Empty
        // unless buildLeadIn() was called. Its LAST entry is clip frame 0 itself
        // -- the segment is closed on the clip at both ends, so the three-frame
        // lookahead reads across the handover without a special case -- which is
        // why leadInSteps() is one less than the table's length, and clip step k
        // sits at episode step leadInSteps() + k.
        std::vector<SynthFrame> leadIn_;

        // The blend-in, indexed by episode step from 0. Unlike the lead-in these
        // OVERLAY the clip rather than preceding it: entry j is what episode step
        // j shows instead of clip frame j - leadInSteps(), and the clip's clock is
        // untouched. Entry blendInSteps() is the clip's own frame there, so the
        // lookahead steps off the end of the table onto the clip with nothing to
        // match up.
        std::vector<SynthFrame> blendIn_;

        // The blend-out, and the episode step its first entry covers. Its LAST
        // entry is the standing frame the run ends on; there is no clip frame
        // after it to be continuous with, because that is the point.
        std::vector<SynthFrame> blendOut_;
        int blendOutFirst_ = -1;

        bool loadMotion(const std::string &path, std::string &error);

        /** True when any synthesised frame exists, i.e. a step may not be a clip frame. */
        bool hasSynthFrames() const {
            return !leadIn_.empty() || !blendIn_.empty() || !blendOut_.empty();
        }

        /**
         * The synthesised frame that stands in for the clip at @p episodeStep, or
         * nullptr when that step is the clip's own. The one place the three tables
         * are resolved, so the lookahead, the reference readout and the error
         * cannot disagree about what the policy was shown.
         */
        const SynthFrame *synthFrame(int episodeStep) const;

        /**
         * Root height at which the default pose stands with its feet on the floor
         * the clip is on -- the floor being the lowest any body gets over the
         * whole clip, since the tables are not referenced to z = 0.
         *
         * The blend-out's target height. Taking the clip's own root height at the
         * last frame instead would hand the rest state a robot crouched, leaping
         * or mid-fall, wherever the clip happened to stop.
         */
        double standRootHeight() const;

        /** Clamp a step index into the clip, matching LoopMode.CLAMP. */
        int clampStep(int clipStep) const;

        /**
         * Table index for @p clipStep, and the root translation its loop count
         * carries. CLAMP clips clamp and report a zero offset; WRAP clips take
         * the index modulo the table and report `loops * wrapDelta`, which has
         * to be added to a root position BEFORE the anchor is applied.
         */
        int resolveStep(int clipStep, Eigen::Vector3d &rootOffset) const;

        /** Clip frame @p k as raw world-frame pieces, before the anchor. */
        void clipFrame(int k, Eigen::Vector3d &rootPos, Eigen::Quaterniond &rootQuat,
                       Eigen::VectorXd &dofPos) const;

        /** Fill a lead-in frame's rot6/key blocks from an already-placed pose. */
        void encodeFrame(SynthFrame &frame) const;
    };

    /** Settings for WorldStateGuard. Defaults are the deployed ones. */
    struct WorldStateGuardConfig {
        bool enabled = true;
        /** Metres of horizontal motion the reference does not explain ... */
        double maxUnexplainedM = 0.5;
        /** ... that may pass within any window this long. */
        double windowS = 0.2;
        /** While a correction is fresh: cap on |v_xy - v_ref_xy|, m/s. */
        double velDeviationMps = 0.5;
        /** How long a correction stays "fresh" after the last rejection, s. */
        double holdS = 0.5;
        /** Control period the guard is stepped at, s. */
        double dt = 0.02;
    };

    /**
     * Keeps a GLITCHING world-state estimate out of the observation.
     *
     * The onboard estimator (docker/estimator) does not only drift: at the
     * takeoff and landing of a jump its horizontal position teleports 1.3-2.4 m
     * within 0.1-0.2 s, with a ~2 m/s horizontal velocity error alongside, and
     * the error stays. A policy that has only ever seen its own tracking error
     * (never above 0.4 m) reads that as the robot being far off the clip and
     * lunges after it -- which is how g1_jumps21 falls on the estimator and
     * never on ground truth.
     *
     * What the guard asks of each control tick is how far the robot moved in xy
     * BEYOND what the reference moved. On ground truth, summed over any 0.2 s,
     * that stays below 0.39 m on every shipped clip -- g1_run and its bundle
     * variant included, at up to 3.75 m/s -- while the glitches reach 2.1 m.
     * So at most maxUnexplainedM of it passes in any windowS; the excess is held
     * out as a persistent xy correction, since the estimator's error does not
     * come back on its own. A later jump the other way (the estimate snapping
     * back) is excess too and cancels it. Height is left alone.
     *
     * While a correction is fresh the horizontal velocity is also held within
     * velDeviationMps of the reference's: the glitch's velocity error outlasts
     * the position jump. Outside a glitch the velocity passes untouched --
     * genuine deviations from the reference velocity reach 1.4 m/s p99 on
     * g1_run, too much to cap permanently.
     *
     * Step it once per control tick, in the frame the reference is placed in,
     * and reset() it whenever the clip is re-anchored.
     */
    class WorldStateGuard {
    public:
        void configure(const WorldStateGuardConfig &cfg);
        const WorldStateGuardConfig &config() const { return cfg_; }

        /** Forget everything: no correction, empty window, zeroed statistics. */
        void reset();

        /**
         * Correct one tick in place (x and y of both vectors only).
         * @param refPos reference root position for this tick, same frame.
         * @param gate   false: take no new rejections (the correction held so far
         *               still applies) -- for ticks whose reference is not moving
         *               with the robot, such as a frozen clock.
         */
        void apply(Eigen::Vector3d &rootPos, Eigen::Vector3d &rootLinVelWorld,
                   const Eigen::Vector3d &refPos, bool gate = true);

        const Eigen::Vector2d &offset() const { return offset_; }
        bool rejectedThisTick() const { return rejected_now_ > 0.0; }
        double rejectedThisTickM() const { return rejected_now_; }
        bool velocityClampedThisTick() const { return vel_clamped_now_; }
        double maxOffsetM() const { return max_offset_; }
        int rejectTicks() const { return reject_ticks_; }
        int velocityClampTicks() const { return vel_clamp_ticks_; }

    private:
        WorldStateGuardConfig cfg_;
        int window_ticks_ = 10;
        int hold_ticks_ = 25;
        std::vector<double> accepted_;   ///< ring buffer, |accepted unexplained step|
        int head_ = 0;
        bool have_prev_ = false;
        Eigen::Vector2d prev_raw_ = Eigen::Vector2d::Zero();
        Eigen::Vector2d prev_ref_ = Eigen::Vector2d::Zero();
        Eigen::Vector2d offset_ = Eigen::Vector2d::Zero();
        int ticks_since_reject_ = 0;
        bool ever_rejected_ = false;
        double rejected_now_ = 0.0;
        bool vel_clamped_now_ = false;
        double max_offset_ = 0.0;
        int reject_ticks_ = 0;
        int vel_clamp_ticks_ = 0;
    };

}  // namespace cpp_control::g1::difftrack
