#pragma once

// Observation assembly for diffsimrl G1 motion-tracking policies (ADD/AMP).
//
// Deliberately free of ROS, MuJoCo and ONNX Runtime: it needs Eigen and
// yaml-cpp (which parses the exporter's JSON -- JSON is a subset of YAML) and
// nothing else. That keeps it unit-testable against a golden trace recorded
// from diffsimrl itself (see tests/difftrack_selftest.cpp), which is the only
// real way to know a reimplementation of somebody else's observation is right:
// the failure modes are quiet ones -- a transposed rotation column, a joint
// permutation, an off-by-one in the lookahead -- that produce a plausible
// vector and a robot that falls over for no visible reason.
//
// Everything here is generated by
//   diffsimrl/code/scripts/export_to_drcl_cpp_control.py
// which writes difftrack_config.json + motion.bin + policy.onnx into
// models/tracker/difftrack/<motion>/.
//
// The observation is 849-dim for the shipped tracking runs:
//
//   char_obs  237  the robot's own state, world frame
//   tar_obs   612  three future reference frames (3 x 204)
//
// char_obs and tar_obs are both expressed in the WORLD frame (the policies were
// trained with imitation.global_obs=true), so the caller must supply a genuine
// world root pose and world linear velocity -- an IMU alone cannot do it. In
// mj_sim that is ground truth off the pelvis framepos/framelinvel/frameangvel
// sensors (G1State.base_pose / base_twist); on hardware it needs a motion
// capture system or an equivalent state estimator.
//
// This file is a port of crl-humanoid-ros' crl_g1_mimiccontroller/DiffTrackObs,
// where these policies were first deployed. The arithmetic is unchanged and is
// held to the same golden trace; only the JSON reader (nlohmann -> yaml-cpp,
// to add no dependency this package did not already have) and the namespace
// differ.

#include <Eigen/Dense>
#include <Eigen/Geometry>

#include <string>
#include <vector>

namespace cpp_control::g1::difftrack {

    /**
     * Rigid placement of the reference clip in the world.
     *
     * Because the observation is world-frame, the policy sees where the clip is
     * in absolute terms. When the episode starts with the robot teleported onto
     * the clip's first frame (reference-state initialisation, what these policies
     * were validated with) that is exactly right and the anchor is the identity.
     *
     * When the robot instead starts wherever it happens to be standing -- always
     * the case on hardware -- the clip has to be moved to it, or the very first
     * observation reports a metres-large position error and a policy trained only
     * on near-zero error is being asked to extrapolate.
     *
     * The transform is deliberately restricted to yaw and horizontal translation:
     *
     *     p -> [Rz(yaw) * p.xy + t,  p.z]        q -> Rz(yaw) * q
     *
     * Height and tilt are left alone -- they are measured against the floor, which
     * does not move, and rotating the clip out of the horizontal plane would ask
     * the policy to track a motion that leans.
     *
     * ROTATING THE CLIP IN THE WORLD IS NOT FREE. These policies were trained
     * with ``imitation.global_obs=true``: the observation carries the root's
     * ABSOLUTE world orientation and its world-frame linear and angular velocity,
     * so the policy is not equivariant to yaw. The translation genuinely cancels
     * -- the reference's position enters the observation relative to the agent in
     * XY, and height is measured against the floor -- but a yaw applied to the
     * clip alone leaves the robot's own orientation and velocity reported in the
     * world frame, which is then a heading the policy never saw at that clip step.
     * Measured on the five shipped lafan1 clips in this workspace's MuJoCo plant,
     * with the observation left in the world frame: a 5 m translation changes the
     * mean root error by less than a millimetre, while a 45 deg rotation roughly
     * quadruples it and 90 deg makes four of five clips fall.
     *
     * That is a property of the OBSERVATION, not of the physics. A yaw about the
     * gravity axis is an exact symmetry of the plant, and the observation is
     * exactly equivariant under it -- rotate the robot and the clip together and
     * every channel rotates with them. So the anchor is safe as long as the robot
     * is rotated with it, which is what toReferenceFrame() does: the clip is
     * placed at the robot in the world, and the observation is then built in the
     * clip's own trained frame, where the policy is back on distribution no matter
     * which way the robot happens to be facing.
     *
     * Use the anchor's yaw ONLY together with toReferenceFrame(). With the
     * observation left in the world frame, keep yaw at 0 and turn the ROBOT onto
     * the clip's heading instead (turn the robot with the locomotion policy, or
     * stand it on the clip's heading by hand).
     */
    struct MotionAnchor {
        double yaw = 0.0;                                   // rotation about +Z
        Eigen::Vector2d translation = Eigen::Vector2d::Zero();
        bool identity = true;

        Eigen::Quaterniond rotation() const {
            return Eigen::Quaterniond(Eigen::AngleAxisd(yaw, Eigen::Vector3d::UnitZ()));
        }
    };

    /**
     * Everything the exporter resolved at build time: the policy's action space,
     * the gains it was trained with, the observation layout, and the kinematic
     * table used to rebuild body poses from joint encoders.
     */
    struct DiffTrackConfig {
        // --- identity -------------------------------------------------------
        std::string sourceRun;
        std::string motionFile;
        // Which training run this directory was exported from, and the tag that
        // keeps it apart from its siblings when several policies of one clip are
        // exported side by side. Both empty for a config exported before they
        // existed, which is why they are read with defaults.
        std::string trainRun;
        std::string variant;
        std::string modelName;   // policy.onnx, relative to the config directory
        std::string motionName;  // motion.bin,  relative to the config directory
        int checkpointIter = -1;

        // --- policy ---------------------------------------------------------
        int numObs = 0;
        int numActions = 0;
        double controlDt = 0.02;

        // Policy/action-space joint order -- the training MJCF's. G1Node's own
        // order comes from the task yaml (unitree_hg motor index == the mjlab MJ
        // index). The two happen to agree for the G1, but the node resolves them
        // BY NAME anyway and refuses a name it cannot place: a silent permutation
        // is the one bug in this pipeline that produces no error at all.
        std::vector<std::string> policyJointNames;
        Eigen::VectorXd defaultAngles;      // (numActions)
        double actionScale = 1.0;
        bool actionClipping = false;
        double actionClipRange = 1.0;

        Eigen::VectorXd jointStiffness;     // (numActions) trained PD gains
        Eigen::VectorXd jointDamping;       // (numActions)
        Eigen::VectorXd jointTorqueLimit;   // (numActions)

        double terminationHeight = 0.0;

        // --- observation layout ---------------------------------------------
        bool globalObs = true;
        bool rootHeightObs = true;
        int charObsDim = 0;
        int tarFeatDim = 0;
        int clipSteps = 0;
        double motionLengthS = 0.0;

        // LoopMode.WRAP -- a cyclic clip (the MimicKit walk) that repeats for as
        // long as the robot is asked to track it, rather than ending on a last
        // frame (every lafan1 clip). The table above holds `wrapCycles` whole
        // reference cycles, chosen by the exporter so that they land on a whole
        // number of control steps; replaying it modulo clipSteps and adding
        // `wrapDelta` to every root position each time round is exactly what the
        // training-time motion library does (MotionLib._calc_loop_offset), so the
        // reference is on the same instants it was trained on indefinitely.
        bool loopWrap = false;
        int wrapCycles = 1;
        Eigen::Vector3d wrapDelta = Eigen::Vector3d::Zero();   // per table repeat
        int numBodies = 0;                  // 31 for the G1 MimicKit model
        int numKeyPoints = 0;
        std::vector<int> tarObsSteps;       // lookahead slots, e.g. {1,2,3}

        std::vector<int> keyBodyIds;                 // indices into the body table
        std::vector<Eigen::Vector3d> keyBodyOffsets;  // local offset per key point

        // Per non-root joint j (body j+1): hinge axis and the DOF driving it.
        // dofIndex < 0 marks a welded joint, whose local rotation is identity.
        std::vector<Eigen::Vector3d> dofAxes;   // (numBodies - 1)
        std::vector<int> dofIndex;              // (numBodies - 1)

        // --- kinematic table (MuJoCo's body tree, flattened) ------------------
        std::vector<std::string> bodyNames;
        std::vector<int> parent;
        std::vector<Eigen::Vector3d> bodyPos;
        std::vector<Eigen::Quaterniond> bodyQuat;
        std::vector<Eigen::Vector3d> jointAxis;
        std::vector<int> jointDof;              // -1 => welded to parent
        std::vector<Eigen::Vector3d> fixedOffset;

        // --- reference-state initialisation (clip frame 0) --------------------
        struct Rsi {
            Eigen::Vector3d rootPos = Eigen::Vector3d::Zero();
            Eigen::Quaterniond rootQuat = Eigen::Quaterniond::Identity();
            Eigen::Vector3d rootLinVel = Eigen::Vector3d::Zero();
            Eigen::Vector3d rootAngVelWorld = Eigen::Vector3d::Zero();
            Eigen::VectorXd dofPos;
            Eigen::VectorXd dofVel;
        } rsi;
    };

    /**
     * The robot state the observation is built from, in POLICY joint order and
     * WORLD frame.
     */
    struct DiffTrackState {
        Eigen::Vector3d rootPos = Eigen::Vector3d::Zero();
        Eigen::Quaterniond rootQuat = Eigen::Quaterniond::Identity();
        Eigen::Vector3d rootLinVelWorld = Eigen::Vector3d::Zero();
        Eigen::Vector3d rootAngVelWorld = Eigen::Vector3d::Zero();
        Eigen::VectorXd dofPos;   // (numActions)
        Eigen::VectorXd dofVel;   // (numActions)
    };

    /**
     * The robot's state re-expressed in the reference clip's own frame.
     *
     * @p anchor is the rigid placement of the clip in the world, so this applies
     * its INVERSE to the robot:
     *
     *     p_ref = Rz(-yaw) * (p_world - [t, 0])      q_ref = Rz(-yaw) * q_world
     *
     * and the same rotation to both velocities. Joint positions and velocities
     * are frame-free and pass through.
     *
     * Feeding computeObs() the result together with an IDENTITY anchor is what
     * makes a yaw anchor safe. The pair (robot, clip) is then in exactly the
     * configuration the policy trained on -- the clip at its recorded world
     * heading, the robot beside it -- whichever way the real robot is facing.
     * The action that comes back is a joint-position target, which carries no
     * frame with it, so nothing has to be rotated on the way out.
     */
    DiffTrackState toReferenceFrame(const DiffTrackState &world, const MotionAnchor &anchor);

    /**
     * One synthesised reference frame of the lead-in, already placed in the
     * world (the anchor has been applied), in the same pieces the clip table
     * stores: root pose, local joint rotations as tan-norm 6-vectors, and key
     * points relative to the root.
     */
    struct LeadInFrame {
        Eigen::Vector3d rootPos = Eigen::Vector3d::Zero();
        Eigen::Quaterniond rootQuat = Eigen::Quaterniond::Identity();
        Eigen::VectorXd dofPos;         // (numActions), for the ghost/diagnostics
        std::vector<float> jointRot6;   // 6 * (numBodies - 1)
        std::vector<float> keyRel;      // 3 * numKeyPoints
    };

    /**
     * Loads the exported artifacts and turns robot state into a policy
     * observation. Stateless with respect to the robot: the episode step and the
     * clip's placement are passed in, so the caller owns the tracking clock.
     */
    class DiffTrackObsBuilder {
    public:
        /**
         * Load difftrack_config.json and the motion.bin sitting beside it.
         * Returns false and fills @p error on any inconsistency; the exporter
         * writes the shapes, so a mismatch here means the files disagree.
         */
        bool load(const std::string &configPath, std::string &error);

        const DiffTrackConfig &config() const { return cfg_; }

        /** Control steps in the reference clip. */
        int clipSteps() const { return cfg_.clipSteps; }

        /**
         * True when the clip loops forever instead of ending on a last frame.
         * A looping clip has no natural completion, so the caller has to decide
         * when to stop tracking it (the node's `play_duration` parameter).
         */
        bool loops() const { return cfg_.loopWrap; }

        /** Control steps of synthesised approach before clip frame 0; 0 if none. */
        int leadInSteps() const {
            return leadIn_.empty() ? 0 : static_cast<int>(leadIn_.size()) - 1;
        }

        /** Control steps in the whole episode: lead-in followed by the clip. */
        int episodeSteps() const { return leadInSteps() + cfg_.clipSteps; }

        /**
         * Assemble the policy observation for @p state at @p episodeStep, with the
         * reference clip placed by @p anchor. @p obs is resized to cfg().numObs.
         *
         * @p episodeStep counts from the start of the lead-in when one has been
         * built, so clip frame 0 is at step leadInSteps(). Steps past the end of
         * the clip reuse the final frame, which is what the training-time motion
         * library does under LoopMode.CLAMP.
         */
        void computeObs(const DiffTrackState &state, int episodeStep,
                        const MotionAnchor &anchor, std::vector<float> &obs) const;

        /**
         * The anchor that places clip frame @p episodeStep at the robot's current
         * horizontal position. Used when the episode does not start from
         * reference-state initialisation.
         *
         * @p matchYaw additionally rotates the clip onto the robot's heading, so
         * that clip frame @p episodeStep lands on the robot's pose exactly rather
         * than only on its position. Read MotionAnchor's note before turning it
         * on: it is only safe when the observation is built in the clip's frame
         * via toReferenceFrame().
         */
        MotionAnchor makeAnchor(const Eigen::Vector3d &robotPos,
                                const Eigen::Quaterniond &robotQuat,
                                int episodeStep, bool matchYaw) const;

        /**
         * Build a lead-in: a synthesised reference segment that starts on the
         * robot exactly as it is standing and arrives at the clip's first frame
         * with that frame's pose AND its velocity.
         *
         * Anchoring alone is not enough to start a clip from a standing robot.
         * It puts the reference where the robot is, but every shipped clip begins
         * mid-motion -- 0.33 to 1.49 m/s, in a joint pose radians away from any
         * stand -- so on the very first control step the reference is already
         * running and the robot is not. The tracking error is a metre inside a
         * second, which is far outside anything the policy saw in training.
         *
         * The lead-in removes that step discontinuity by interpolating. Each
         * quantity follows a cubic Hermite in time, clamped to the measured robot
         * state and its zero velocity at one end and to the clip's first frame and
         * ITS velocity at the other, so the reference is C1 across the handover:
         * position and velocity both match where the clip takes over. Choosing the
         * horizontal travel as the trapezoid ``(v0 + v1) * T / 2`` makes the root's
         * translation a constant-acceleration ramp, which is what the anchor's
         * translation is solved for -- the reference accelerates smoothly from the
         * robot's standing speed up to the clip's entry speed rather than jumping.
         *
         * Returns the anchor to use for the whole episode (the clip's placement is
         * a consequence of where the lead-in has to end) and leaves the synthesised
         * frames in the builder. @p durationS <= 0 clears any lead-in and gives the
         * plain anchor of makeAnchor().
         *
         * Measured on the five shipped clips: once the robot is turned onto the
         * clip's heading (@p matchYaw false), a lead-in is NOT what makes a
         * standing start work, and a long one actively breaks it -- the policies
         * have no standing behaviour, so parking them in front of a slow reference
         * topples the robot in about a second. Leave it at 0 unless a specific
         * clip measures better with it.
         */
        MotionAnchor buildLeadIn(const DiffTrackState &robot, double durationS,
                                 bool matchYaw);

        /** Discard a lead-in built earlier (episode restart). */
        void clearLeadIn() { leadIn_.clear(); }

        /**
         * Policy action -> joint position target, in POLICY joint order.
         * target = default + action_scale * action, optionally clipped, exactly
         * as utils/actuator_params.py:process_policy_actions_numpy does.
         */
        void actionToJointTarget(const Eigen::VectorXd &action,
                                 Eigen::VectorXd &target) const;

        /** World body poses for the tracked bodies (exposed for diagnostics). */
        void forwardKinematics(const Eigen::Vector3d &rootPos,
                               const Eigen::Quaterniond &rootQuat,
                               const Eigen::VectorXd &dofPos,
                               std::vector<Eigen::Vector3d> &bodyPos,
                               std::vector<Eigen::Quaterniond> &bodyQuat) const;

        /**
         * Reference root pose and joint pose at @p episodeStep, with @p anchor
         * applied. Used for the tracking-error readout and the ghost overlay.
         * Steps inside the lead-in report the synthesised approach frame.
         */
        void referencePose(int episodeStep, const MotionAnchor &anchor,
                           Eigen::Vector3d &rootPos, Eigen::Quaterniond &rootQuat,
                           Eigen::VectorXd &dofPos) const;

    private:
        DiffTrackConfig cfg_;

        // motion.bin. The reference is stored as raw world-frame pieces rather
        // than as the finished feature vector, because the anchor has to be
        // applied before the 6D rotation encoding is formed -- tan-norm does not
        // commute with a yaw rotation, so a precomputed feature block cannot be
        // rotated after the fact.
        std::vector<float> tarRootPos_;    // (S, clipSteps, 3)      world
        std::vector<float> tarRootQuat_;   // (S, clipSteps, 4)      world, wxyz
        std::vector<float> tarJointRot6_;  // (S, clipSteps, 6*(nb-1)) local, anchor-invariant
        std::vector<float> tarKeyRel_;     // (S, clipSteps, K*3)    world-oriented, root-relative
        std::vector<float> refRootPos_;    // (clipSteps, 3)
        std::vector<float> refRootQuat_;   // (clipSteps, 4)  wxyz
        std::vector<float> refDofPos_;     // (clipSteps, numActions)

        // Synthesised approach onto clip frame 0, indexed by episode step. Empty
        // unless buildLeadIn() was called. Its LAST entry is clip frame 0 itself
        // -- the segment is closed on the clip at both ends, so the three-frame
        // lookahead reads across the handover without a special case -- which is
        // why leadInSteps() is one less than the table's length, and clip step k
        // sits at episode step leadInSteps() + k.
        std::vector<LeadInFrame> leadIn_;

        bool loadMotion(const std::string &path, std::string &error);

        /** Clamp a step index into the clip, matching LoopMode.CLAMP. */
        int clampStep(int clipStep) const;

        /**
         * Table index for @p clipStep, and the root translation its loop count
         * carries. CLAMP clips clamp and report a zero offset; WRAP clips take
         * the index modulo the table and report `loops * wrapDelta`, which has
         * to be added to a root position BEFORE the anchor is applied.
         */
        int resolveStep(int clipStep, Eigen::Vector3d &rootOffset) const;

        /** Clip frame @p k as raw world-frame pieces, before the anchor. */
        void clipFrame(int k, Eigen::Vector3d &rootPos, Eigen::Quaterniond &rootQuat,
                       Eigen::VectorXd &dofPos) const;

        /** Fill a lead-in frame's rot6/key blocks from an already-placed pose. */
        void encodeFrame(LeadInFrame &frame) const;
    };

}  // namespace cpp_control::g1::difftrack
