#!/usr/bin/env python3
"""Generate an mj_sim scene with the G1 standing on the ground.

The shipped scene (`assets: g1/scene_flat.xml`) holds the pelvis in the air:

    <equality>
        <weld name="world_root" active="true" body1="pelvis" relpose="0 0 -1.0 ..."/>
    </equality>

which is right for bring-up — you can watch a controller move the limbs without
it falling over — and is what the readme's "to keep robot on/off ground, right
side bar under Equality, toggle `world_root`" refers to. It is also exactly the
kind of thing that must not be left on for a transfer result: anything a weld
holds up is not a locomotion measurement. mj_sim can only clear it from the
viewer (the `Y` key), so an unattended run needs a scene that never had it.

This writes such a scene, by copying the robot model with two surgical edits and
adding a scene file beside it:

    <out>/g1/g1_bm_ground.xml      weld inactive; meshdir made absolute so the
                                   copy still finds the original meshes
    <out>/g1/scene_flat_ground.xml includes the stock terrain + that model

Point mj_sim at it with SIM_ASSETS_PATH=<out> and
`model_path: g1/scene_flat_ground.xml`, which is what
`run_difftrack_sim2sim.sh` does.

The output is generated, machine-local and disposable: regenerate it rather than
editing it, and never commit it.

    python3 scripts/make_sim2sim_scene.py [--assets $SIM_ASSETS_PATH] [--out DIR]
"""

import argparse
import os
import re
import sys
import tempfile


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--assets", default=os.environ.get("SIM_ASSETS_PATH", ""),
                    help="asset root (default: $SIM_ASSETS_PATH)")
    ap.add_argument("--out", default=os.path.join(tempfile.gettempdir(),
                                                  "cpp_control_sim_scene"),
                    help="where to write the generated scene")
    ap.add_argument("--model", default="g1/g1_bm.xml",
                    help="robot model to copy, relative to --assets")
    ap.add_argument("--terrain", default="terrain/flat_ground.xml",
                    help="terrain to include, relative to --assets")
    ap.add_argument("--init-from", default="",
                    help="difftrack_config.json: start the robot ON the clip's first "
                         "frame (reference-state initialisation) instead of the "
                         "model's own pose")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    if not args.assets:
        sys.exit("no asset root: pass --assets or set SIM_ASSETS_PATH "
                 "(source workflows/conda_env/runenv.sh)")
    src = os.path.join(args.assets, args.model)
    terrain = os.path.join(args.assets, args.terrain)
    for path in (src, terrain):
        if not os.path.isfile(path):
            sys.exit(f"no such asset: {path}")

    xml = open(src).read()

    # 1. The weld. Matched on the name so a scene without it (or with a second
    #    equality) is not silently mangled.
    xml, n = re.subn(r'(<weld\b[^>]*\bname="world_root"[^>]*\bactive=")true(")',
                     r"\1false\2", xml)
    if n != 1:
        sys.exit(f"expected exactly one active world_root weld in {src}, found {n}. "
                 "The scene changed upstream — read it before trusting this script.")

    # 2. meshdir. The copy lives somewhere else, so a relative mesh directory
    #    would resolve against the wrong place: MuJoCo then fails to load with a
    #    missing-mesh error rather than anything about this script.
    mesh_abs = os.path.join(os.path.dirname(src), "meshes") + os.sep
    xml, n = re.subn(r'(<compiler\b[^>]*\bmeshdir=")[^"]*(")',
                     lambda m: m.group(1) + mesh_abs + m.group(2), xml, count=1)
    if n != 1:
        sys.exit(f"no <compiler meshdir=...> in {src}; cannot relocate the model")

    banner = (f"<!-- GENERATED by cpp_control/scripts/make_sim2sim_scene.py from\n"
              f"     {src}\n"
              f"     world_root weld disabled (the robot stands on the ground).\n"
              f"     Machine-local and disposable: regenerate, do not edit. -->\n")

    out_g1 = os.path.join(args.out, "g1")
    os.makedirs(out_g1, exist_ok=True)
    model_out = os.path.join(out_g1, "g1_bm_ground.xml")
    with open(model_out, "w") as f:
        f.write(banner + xml)

    scene_out = os.path.join(out_g1, "scene_flat_ground.xml")
    with open(scene_out, "w") as f:
        f.write(banner + f"""<mujoco model="g1_flat_ground">
<include file="{terrain}"/>
<include file="g1_bm_ground.xml"/>
</mujoco>
""")

    if args.init_from:
        scene_out = _bake_initial_pose(scene_out, args.init_from, banner)

    rel = os.path.relpath(scene_out, args.out)
    if not args.quiet:
        print(f"[scene] {scene_out}")
        print(f"[scene] SIM_ASSETS_PATH={args.out}  model_path={rel}")
    else:
        # One line the caller can read: the root mj_sim wants, and the path to
        # put in its config, which differs between the plain and the RSI scene.
        print(f"{args.out} {rel}")


def _bake_initial_pose(scene_path, config_path, banner):
    """Rewrite the scene so `mj_resetData` lands on the clip's first frame.

    Reference-state initialisation is how these policies were trained and
    evaluated: the episode starts with the robot ON the reference, not standing
    beside it. There is no way to ask mj_sim for that — it resets to the model's
    own pose and offers the operator a keyframe only behind a viewer key — so
    the pose has to be the model's own.

    MuJoCo has no single "initial joint angle" that does this, and each half of
    the answer is wrong on its own:

      * `ref` alone moves qpos0 to theta but shifts the joint's zero with it, so
        the robot at reset is still in the XML pose while the encoders claim
        theta. The observation would be right and the robot wrong.
      * baking theta into the body frame alone puts the robot in the clip's pose
        but leaves qpos at 0, so the encoders — which is all the controller
        reads — report a robot that is not the one standing there.

    Both together are exact. Set `ref = theta` AND `quat <- quat * R(axis,
    theta)`: the joint contributes R(axis, qpos - ref), which is identity at
    reset, so the configuration is the body frames alone, i.e. the clip's pose;
    and qpos reads theta. Every other joint coordinate keeps its old meaning —
    at any qpos = x the configuration is quat * R(axis, theta) * R(axis, x -
    theta) = quat * R(axis, x), exactly as before — so ranges, limits and the
    position servos are untouched. This needs the hinge to pass through the body
    origin, which every G1 joint does (the exporter asserts it) and which is
    checked below.

    What cannot be baked is VELOCITY: qvel is always zero at reset, while these
    clips start moving (g1_walk enters at ~0.97 m/s). The controller's
    `lead_in_duration` exists for exactly that gap — it ramps the reference from
    the robot's actual velocity up to the clip's.
    """
    import json
    import math

    import mujoco

    conf = json.load(open(config_path))
    rsi = conf["rsi"]
    names = conf["policy_joint_names"]
    dof = rsi["dof_pos"]

    spec = mujoco.MjSpec.from_file(scene_path)

    for name, angle in zip(names, dof):
        joint = spec.joint(name)
        if joint is None:
            sys.exit(f"{scene_path} has no joint '{name}' — this scene is not the "
                     "robot the policy was exported for")
        if int(joint.type) != int(mujoco.mjtJoint.mjJNT_HINGE):
            sys.exit(f"joint '{name}' is not a hinge; cannot bake an initial angle")
        if max(abs(v) for v in joint.pos) > 1e-9:
            sys.exit(f"joint '{name}' is not at its body's origin ({list(joint.pos)}); "
                     "rotating the body frame would not be the joint rotation")
        axis = list(joint.axis)
        n = math.sqrt(sum(v * v for v in axis))
        half = 0.5 * angle
        sin = math.sin(half) / n
        jq = [math.cos(half), axis[0] * sin, axis[1] * sin, axis[2] * sin]
        joint.ref = angle
        body = joint.parent
        q = list(body.quat)
        body.quat = [
            q[0] * jq[0] - q[1] * jq[1] - q[2] * jq[2] - q[3] * jq[3],
            q[0] * jq[1] + q[1] * jq[0] + q[2] * jq[3] - q[3] * jq[2],
            q[0] * jq[2] - q[1] * jq[3] + q[2] * jq[0] + q[3] * jq[1],
            q[0] * jq[3] + q[1] * jq[2] - q[2] * jq[1] + q[3] * jq[0],
        ]

    root = spec.body(spec.joint(names[0]).parent.name)   # any actuated body's chain
    while root.parent is not None and root.parent.name not in ("world", ""):
        root = root.parent
    root.pos = list(rsi["root_pos"])
    root.quat = list(rsi["root_quat_wxyz"])

    out = os.path.join(os.path.dirname(scene_path), "scene_flat_rsi.xml")
    with open(out, "w") as f:
        f.write(banner + spec.to_xml())

    # Prove it: the compiled reset pose must be the clip's frame, to round-off.
    model = mujoco.MjModel.from_xml_path(out)
    data = mujoco.MjData(model)
    mujoco.mj_resetData(model, data)
    mujoco.mj_forward(model, data)
    got = [data.qpos[model.jnt_qposadr[mujoco.mj_name2id(
        model, mujoco.mjtObj.mjOBJ_JOINT, n)]] for n in names]
    err = max(abs(a - b) for a, b in zip(got, dof))
    root_err = max(abs(data.qpos[i] - rsi["root_pos"][i]) for i in range(3))
    # 1e-5 rather than round-off: MjSpec writes the XML in float32-ish decimal,
    # so a bake that is exact in memory comes back ~5e-7 off. Anything larger
    # than this is a real disagreement, not serialisation.
    if err > 1e-5 or root_err > 1e-5:
        sys.exit(f"baked initial pose is off by {err:.2e} rad / {root_err:.2e} m; "
                 "the scene is not what the config describes")
    print(f"[scene] reference-state start: clip frame 0 to {err:.1e} rad / "
          f"{root_err:.1e} m (velocity cannot be baked; qvel starts at zero)")
    return out


if __name__ == "__main__":
    main()
